default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres

development:
  <<: *default
  database: order_manager_development

test: &test
  <<: *default
  database: order_manager_test

production:
  <<: *default
  url: postgres://postgres:postgres@localhost:5432/db

cucumber:
  <<: *test
