default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: order_manager_development

test: &test
  <<: *default
  database: order_manager_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cucumber:
  <<: *test
